apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirect-oldsite
  namespace: default
spec:
  redirectRegex:
    regex: ^https?://(www.)?einados\.com/(.*)
    replacement: https://agrohacksstuff.io/$2
    permanent: true
